### ISSUE TITLE
Infinite Loading after Lockpicking

### ISSUE THREAD

**Issue by scarfoxed** [GemsHD/gems-houserobbery#1]
having an occassional issue where when you lockpick the door and go to enter it goes to a black screen with a loading circle and stays there until you f8 quit - only errors in tx admin console are 

[script:gem-housero] SCRIPT ERROR: @gem-houserobbery/server/server.lua:127: No such export DropJewels in resource gems-jewels
[script:gem-housero] SCRIPT ERROR: @gem-houserobbery/server/server.lua:160: No such export HasBuff in resource ps-buffs

**Comment by GemsHD** [comment]
Should be good now if you want to pull the latest version

**Comment by scarfoxed** [comment]
Turns out, its because I dont have any of K4mb1s extra shells - qb-interior doesnt come with furnitured_lowapart so the CreateFurniLow just snags at that point. Only one it comes with is furnitured_midapart
